# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-15 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181215_1230'),
    ]

    operations = [
    ]
