# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-13 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
